import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Truck',
      collapsible: true,
      collapsed: true,
      className: 'sidebar-project',
      link: {
        type: 'generated-index',
        title: 'Truck',
        description: 'Gestao de frotas e manutencao — engenharia, produto e projeto.',
        slug: '/truck',
      },
      items: [{type: 'autogenerated', dirName: 'truck'}],
    },
    {
      type: 'category',
      label: 'Hub',
      collapsible: true,
      collapsed: true,
      className: 'sidebar-project',
      link: {
        type: 'generated-index',
        title: 'Hub',
        description: 'SSO, billing e assinaturas — engenharia, produto e projeto.',
        slug: '/hub',
      },
      items: [{type: 'autogenerated', dirName: 'hub'}],
    },
    {
      type: 'category',
      label: 'Design System',
      collapsible: true,
      collapsed: true,
      className: 'sidebar-project',
      link: {
        type: 'generated-index',
        title: 'Design System',
        description: '@facter/ds-core — componentes, tokens e guias.',
        slug: '/design-system',
      },
      items: [{type: 'autogenerated', dirName: 'design-system'}],
    },
    {
      type: 'category',
      label: 'Onboarding',
      collapsible: true,
      collapsed: true,
      className: 'sidebar-project',
      link: {
        type: 'generated-index',
        title: 'Onboarding',
        description: 'Setup local, stack overview e guia de contribuicao.',
        slug: '/onboarding',
      },
      items: [{type: 'autogenerated', dirName: 'onboarding'}],
    },
  ],
};

export default sidebars;
